/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Neil
 */
import java.time.*;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.filechooser.*;
import java.awt.Image;
import java.io.File;
import javax.swing.JFileChooser;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
public class AddNewMember extends javax.swing.JFrame {

    /**
     * Creates new form AddNewMember
     */
    String pathPhoto = "";
    public AddNewMember() {
        initComponents();
        DateTimeFormatter format = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDateTime DateTime = LocalDateTime.now();
        String formattedDate = DateTime.format(format);
        startDateField.setText(formattedDate);
    }
    
    public static boolean lettersOnly(String s){
        for (int i = 0; i < s.length(); i++){
            char x = s.charAt(i);
            if(!Character.isLetter(x)){
                return false;
            }
        }
        return true;
    }
    
    public static boolean digitsOnly(String s){
        for (int i = 0; i < s.length(); i++){
            char x = s.charAt(i);
            if(!Character.isDigit(x)){
                return false;
            }
        }
        return true;
    }
    
    public ImageIcon resizeImage(String ImagePath){
        ImageIcon theImage = new ImageIcon(ImagePath);
        Image img = theImage.getImage();
        Image newimage = img.getScaledInstance(photoLabel.getWidth(), photoLabel.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon  image = new ImageIcon(newimage);
        return image;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Gender = new javax.swing.ButtonGroup();
        ConfirmJdialog = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        YesSaveBTN = new javax.swing.JButton();
        CancelSaveBTN = new javax.swing.JButton();
        NoSaveBTN = new javax.swing.JButton();
        NameSaveLBL = new javax.swing.JLabel();
        SurnameSaveLBL = new javax.swing.JLabel();
        DOBSaveLBL = new javax.swing.JLabel();
        GenderSaveLBL = new javax.swing.JLabel();
        PhoneSaveLBL = new javax.swing.JLabel();
        EmailSaveLBL = new javax.swing.JLabel();
        PositionSaveLBL = new javax.swing.JLabel();
        TeamSaveLBL = new javax.swing.JLabel();
        StartDateSaveLBL = new javax.swing.JLabel();
        EndDateSaveLBL = new javax.swing.JLabel();
        FilePathSaveLBL = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        surnameField = new javax.swing.JTextField();
        namefield = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        femaleRB = new javax.swing.JRadioButton();
        maleRB = new javax.swing.JRadioButton();
        teamCB = new javax.swing.JComboBox<>();
        positionCB = new javax.swing.JComboBox<>();
        phoneField = new javax.swing.JTextField();
        clearBTN = new javax.swing.JButton();
        saveBTN = new javax.swing.JButton();
        photoBTN = new javax.swing.JButton();
        DOBField = new javax.swing.JFormattedTextField();
        startDateField = new javax.swing.JFormattedTextField();
        endDateField = new javax.swing.JFormattedTextField();
        photoLabel = new javax.swing.JLabel();

        ConfirmJdialog.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                ConfirmJdialogWindowActivated(evt);
            }
        });

        jLabel12.setText("Are you sure you want to save this data:");

        jLabel14.setText("Name:");

        jLabel15.setText("Surname:");

        jLabel16.setText("DOB:");

        jLabel17.setText("Gender:");

        jLabel18.setText("Phone:");

        jLabel19.setText("Email:");

        jLabel20.setText("Team:");

        jLabel21.setText("Position:");

        jLabel22.setText("Start Date: ");

        jLabel23.setText("End Date: ");

        jLabel24.setText("File Path:");

        YesSaveBTN.setText("Yes");
        YesSaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YesSaveBTNActionPerformed(evt);
            }
        });

        CancelSaveBTN.setText("Cancel");
        CancelSaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelSaveBTNActionPerformed(evt);
            }
        });

        NoSaveBTN.setText("No");
        NoSaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoSaveBTNActionPerformed(evt);
            }
        });

        NameSaveLBL.setText("jLabel13");

        SurnameSaveLBL.setText("jLabel13");

        DOBSaveLBL.setText("jLabel13");

        GenderSaveLBL.setText("jLabel13");

        PhoneSaveLBL.setText("jLabel13");

        EmailSaveLBL.setText("jLabel13");

        PositionSaveLBL.setText("jLabel13");

        TeamSaveLBL.setText("jLabel13");

        StartDateSaveLBL.setText("jLabel13");

        EndDateSaveLBL.setText("jLabel13");

        FilePathSaveLBL.setText("jLabel13");

        javax.swing.GroupLayout ConfirmJdialogLayout = new javax.swing.GroupLayout(ConfirmJdialog.getContentPane());
        ConfirmJdialog.getContentPane().setLayout(ConfirmJdialogLayout);
        ConfirmJdialogLayout.setHorizontalGroup(
            ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmJdialogLayout.createSequentialGroup()
                .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ConfirmJdialogLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(YesSaveBTN)
                        .addGap(57, 57, 57)
                        .addComponent(NoSaveBTN)
                        .addGap(63, 63, 63)
                        .addComponent(CancelSaveBTN))
                    .addGroup(ConfirmJdialogLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ConfirmJdialogLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NameSaveLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ConfirmJdialogLayout.createSequentialGroup()
                        .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(ConfirmJdialogLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ConfirmJdialogLayout.createSequentialGroup()
                                    .addGap(73, 73, 73)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ConfirmJdialogLayout.createSequentialGroup()
                                    .addGap(73, 73, 73)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(ConfirmJdialogLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(ConfirmJdialogLayout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, ConfirmJdialogLayout.createSequentialGroup()
                                    .addGap(73, 73, 73)
                                    .addComponent(jLabel22))
                                .addGroup(ConfirmJdialogLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StartDateSaveLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PositionSaveLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenderSaveLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SurnameSaveLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DOBSaveLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PhoneSaveLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmailSaveLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TeamSaveLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EndDateSaveLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FilePathSaveLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        ConfirmJdialogLayout.setVerticalGroup(
            ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConfirmJdialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameSaveLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SurnameSaveLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DOBSaveLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenderSaveLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneSaveLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailSaveLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TeamSaveLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PositionSaveLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StartDateSaveLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EndDateSaveLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FilePathSaveLBL))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConfirmJdialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(YesSaveBTN)
                    .addComponent(NoSaveBTN)
                    .addComponent(CancelSaveBTN))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sharks Waterpolo Club");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 42)); // NOI18N
        jLabel1.setText("Add a New Member");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Surname");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Date Of Birth");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Phone");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Email");

        surnameField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        surnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surnameFieldActionPerformed(evt);
            }
        });

        namefield.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });

        emailField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Gender");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Team");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Position");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Start Date");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("End Date");

        Gender.add(femaleRB);
        femaleRB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        femaleRB.setSelected(true);
        femaleRB.setText("Female");
        femaleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRBActionPerformed(evt);
            }
        });

        Gender.add(maleRB);
        maleRB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        maleRB.setText("Male");
        maleRB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRBActionPerformed(evt);
            }
        });

        teamCB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        teamCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Development", "U10", "U12", "U14", "U16", "U20", "Senior" }));
        teamCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamCBActionPerformed(evt);
            }
        });

        positionCB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        positionCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Beginner", "Goalkeeper", "Second Goalkeeper", "1", "2", "3", "4", "5", "6" }));

        phoneField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneFieldActionPerformed(evt);
            }
        });

        clearBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearBTN.setText("Clear All");
        clearBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearBTNMouseClicked(evt);
            }
        });

        saveBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        saveBTN.setText("Save");
        saveBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveBTNMouseClicked(evt);
            }
        });
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });

        photoBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        photoBTN.setText("Add Photo");
        photoBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                photoBTNMouseClicked(evt);
            }
        });
        photoBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                photoBTNActionPerformed(evt);
            }
        });

        DOBField.setText("dd/MM/yyyy");
        DOBField.setToolTipText("dd/mm/yyyy");
        DOBField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DOBFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                DOBFieldFocusLost(evt);
            }
        });
        DOBField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DOBFieldMouseClicked(evt);
            }
        });
        DOBField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBFieldActionPerformed(evt);
            }
        });

        startDateField.setText("dd/MM/yyyy");
        startDateField.setToolTipText("dd/mm/yyyy");
        startDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startDateFieldActionPerformed(evt);
            }
        });

        endDateField.setText("dd/MM/yyyy");
        endDateField.setToolTipText("dd/mm/yyyy");
        endDateField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                endDateFieldFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                endDateFieldFocusLost(evt);
            }
        });
        endDateField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                endDateFieldMouseClicked(evt);
            }
        });
        endDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endDateFieldActionPerformed(evt);
            }
        });

        photoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(surnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(emailField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                        .addComponent(phoneField, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                                    .addComponent(DOBField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel9))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(maleRB, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(femaleRB, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(teamCB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(positionCB, 0, 180, Short.MAX_VALUE))
                                    .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(endDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                .addComponent(photoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264))))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(photoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(saveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(femaleRB)
                    .addComponent(maleRB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teamCB, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(surnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(positionCB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(DOBField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(endDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(photoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(photoBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void surnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_surnameFieldActionPerformed

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void femaleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_femaleRBActionPerformed

    private void maleRBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maleRBActionPerformed

    private void phoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneFieldActionPerformed

    private void teamCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teamCBActionPerformed

    private void photoBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_photoBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_photoBTNActionPerformed

    private void photoBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_photoBTNMouseClicked
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg", "png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION){
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            pathPhoto = path;
            photoLabel.setIcon(resizeImage(path));
        }
    }//GEN-LAST:event_photoBTNMouseClicked

    private void saveBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveBTNMouseClicked
        String name = namefield.getText();
        String surname = surnameField.getText();
        String phone = phoneField.getText();
        String DOB = DOBField.getText();
        String email = emailField.getText();
        String startDate = startDateField.getText();
        String endDate = endDateField.getText();
        String team = teamCB.getSelectedItem().toString();
        String position = positionCB.getSelectedItem().toString();
        String gender = "";
        LocalDate Now = LocalDate.now();
        
        if (maleRB.isSelected()){
            gender = "Male";
        }else{
            gender = "Female";
        }
        
        boolean validName = false;
        boolean validSurname = false;
        boolean validPhone = false;
        boolean validDate = true;
        boolean validDate2 = true;
        boolean validDOB = true;
        
        if (!name.isBlank()){
            validName = lettersOnly(name);
        }
        if (!surname.isBlank()){
            validSurname = lettersOnly(surname);
        }
        if (!phone.isBlank()){
           validPhone = digitsOnly(phone); 
        }else{
            validPhone = true;
        }
        
        DateTimeFormatter format = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate DOB1 = null;
        LocalDate startDate1 = null;
        LocalDate endDate1 = null;
        
        try {
            DOB1 = LocalDate.parse(DOB, format);
        } catch (Exception DateTimeParseException) {
            validDOB = false;
        }
        try {
            startDate1 = LocalDate.parse(startDate, format);
        } catch (Exception DateTimeParseException) {
            validDate = false;
        }
        try {
            endDate1 = LocalDate.parse(endDate, format);
            
            if (endDate1.isBefore(startDate1)){
                validDate2 = false;
            }
        } catch (Exception DateTimeParseException) {
            if (endDate.equals("dd/MM/yyyy")){
                validDate2 = true;
            }else{
                validDate2 = false;
            }
        }
        
       if (validDate){
           if (startDate1.isAfter(Now)){
               validDate = false;
           }
       }
       
       if (validDOB && DOB1.isAfter(Now)){
           validDOB = false;
       }
       
       if(!validName){
           JOptionPane.showMessageDialog(this, "Error in Name");
       }
       if(!validSurname){
           JOptionPane.showMessageDialog(this, "Error in Surname");
       }
       if (!validPhone){
           JOptionPane.showMessageDialog(this, "Error in phone");
       }
       if(!validDOB){
           JOptionPane.showMessageDialog(this, "Error in Date of Birth");
       }
       if(!validDate || !validDate2){
           JOptionPane.showMessageDialog(this, "Error in membership dates");
       }
       
       if(validName && validSurname && validPhone && validDOB && validDate && validDate2){
           int confirm = JOptionPane.showConfirmDialog(this, ("Are you sure you want to save this data:\n")+ ("Name: " + name + "\n") + ("Surname: " + surname + "\n") + ("Date of Birth: " + DOB + "\n") + ("Gender: " + gender + "\n") + ("Phone: " + phone + "\n") + ("Email: " + email + "\n") + ("Team: " + team + "\n") + ("Position: " + position + "\n") + ("Start Date: " + startDate + "\n") + ("End Date: " + endDate + "\n") + ("FilePath: " + pathPhoto + "\n"));
           if (confirm == 0){
               try {
                   File myFile = new File("Members.csv");
                   if (!myFile.exists()){
                       myFile.createNewFile();
                   }

                   FileWriter Writer = new FileWriter(myFile, true);
                   BufferedWriter buffWriter = new BufferedWriter(Writer);
                   buffWriter.write(name + "," + surname + "," + team + "\n");
                   buffWriter.close();
               } catch (IOException ex) {
                   System.out.println("Something went wrong...");
               }
               this.dispose();
           }
       }
    }//GEN-LAST:event_saveBTNMouseClicked

    private void DOBFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBFieldActionPerformed

    private void startDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startDateFieldActionPerformed

    private void endDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endDateFieldActionPerformed

    private void clearBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBTNMouseClicked
        namefield.setText("");
        surnameField.setText("");
        DOBField.setText("");
        phoneField.setText("");
        emailField.setText("");
        maleRB.setSelected(false);
        femaleRB.setSelected(true);
        teamCB.setSelectedIndex(0);
        positionCB.setSelectedIndex(0);
        startDateField.setText("");
        endDateField.setText("");
        photoLabel.setIcon(null);
    }//GEN-LAST:event_clearBTNMouseClicked

    private void DOBFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DOBFieldMouseClicked

    }//GEN-LAST:event_DOBFieldMouseClicked

    private void endDateFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_endDateFieldMouseClicked

    }//GEN-LAST:event_endDateFieldMouseClicked

    private void DOBFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBFieldFocusLost
        String DOB = DOBField.getText();
        
        if (DOB.isBlank()){
            DOBField.setText("dd/MM/yyyy");
        }
    }//GEN-LAST:event_DOBFieldFocusLost

    private void endDateFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_endDateFieldFocusLost
        String ED = endDateField.getText();
        
        if (ED.isBlank()){
            endDateField.setText("dd/MM/yyyy");
        }
    }//GEN-LAST:event_endDateFieldFocusLost

    private void DOBFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DOBFieldFocusGained
        String DOB = DOBField.getText();
        
        if (DOB.equals("dd/MM/yyyy")){
           DOBField.setText(""); 
        }
    }//GEN-LAST:event_DOBFieldFocusGained

    private void endDateFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_endDateFieldFocusGained
        String ED = endDateField.getText();
        
        if (ED.equals("dd/MM/yyyy")){
           endDateField.setText(""); 
        }
    }//GEN-LAST:event_endDateFieldFocusGained

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
         
    }//GEN-LAST:event_saveBTNActionPerformed

    private void YesSaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YesSaveBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_YesSaveBTNActionPerformed

    private void CancelSaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelSaveBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelSaveBTNActionPerformed

    private void NoSaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoSaveBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoSaveBTNActionPerformed

    private void ConfirmJdialogWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_ConfirmJdialogWindowActivated
        JOptionPane.showMessageDialog(this, "It loaded!");
    }//GEN-LAST:event_ConfirmJdialogWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelSaveBTN;
    private javax.swing.JDialog ConfirmJdialog;
    private javax.swing.JFormattedTextField DOBField;
    private javax.swing.JLabel DOBSaveLBL;
    private javax.swing.JLabel EmailSaveLBL;
    private javax.swing.JLabel EndDateSaveLBL;
    private javax.swing.JLabel FilePathSaveLBL;
    private javax.swing.ButtonGroup Gender;
    private javax.swing.JLabel GenderSaveLBL;
    private javax.swing.JLabel NameSaveLBL;
    private javax.swing.JButton NoSaveBTN;
    private javax.swing.JLabel PhoneSaveLBL;
    private javax.swing.JLabel PositionSaveLBL;
    private javax.swing.JLabel StartDateSaveLBL;
    private javax.swing.JLabel SurnameSaveLBL;
    private javax.swing.JLabel TeamSaveLBL;
    private javax.swing.JButton YesSaveBTN;
    private javax.swing.JButton clearBTN;
    private javax.swing.JTextField emailField;
    private javax.swing.JFormattedTextField endDateField;
    private javax.swing.JRadioButton femaleRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton maleRB;
    private javax.swing.JTextField namefield;
    private javax.swing.JTextField phoneField;
    private javax.swing.JButton photoBTN;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JComboBox<String> positionCB;
    private javax.swing.JButton saveBTN;
    private javax.swing.JFormattedTextField startDateField;
    private javax.swing.JTextField surnameField;
    private javax.swing.JComboBox<String> teamCB;
    // End of variables declaration//GEN-END:variables
}
